/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.project2_calculatrice;

import java.awt.Button;
import java.awt.Panel;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author youcef
 */
public class calculatrice extends javax.swing.JFrame {

    /**
     * Creates new form calculatrice
     */
    public calculatrice() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        num0 = new javax.swing.JButton();
        btn_off = new javax.swing.JButton();
        tf_display = new javax.swing.JTextField();
        num1 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        num2 = new javax.swing.JButton();
        tbn_point = new javax.swing.JButton();
        num3 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        num4 = new javax.swing.JButton();
        tbn_mult = new javax.swing.JButton();
        num5 = new javax.swing.JButton();
        tbn_minus = new javax.swing.JButton();
        num6 = new javax.swing.JButton();
        tbn_add = new javax.swing.JButton();
        num7 = new javax.swing.JButton();
        tbn_result = new javax.swing.JButton();
        num8 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        num9 = new javax.swing.JButton();
        tbn_dir = new javax.swing.JButton();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        num0.setBackground(new java.awt.Color(255, 255, 255));
        num0.setFont(new java.awt.Font("Courier New", 3, 24)); // NOI18N
        num0.setForeground(new java.awt.Color(0, 0, 0));
        num0.setText("0");
        num0.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        num0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                display_Numers_OnScreen(evt);
            }
        });

        btn_off.setBackground(new java.awt.Color(255, 0, 0));
        btn_off.setFont(new java.awt.Font("Courier New", 3, 20)); // NOI18N
        btn_off.setForeground(new java.awt.Color(255, 255, 255));
        btn_off.setText("OFF");
        btn_off.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_off.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_offActionPerformed(evt);
            }
        });

        tf_display.setBackground(new java.awt.Color(255, 255, 255));
        tf_display.setForeground(new java.awt.Color(0, 0, 0));
        tf_display.setFocusable(false);

        num1.setBackground(new java.awt.Color(255, 255, 255));
        num1.setFont(new java.awt.Font("Courier New", 3, 24)); // NOI18N
        num1.setForeground(new java.awt.Color(0, 0, 0));
        num1.setText("1");
        num1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        num1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                display_Numers_OnScreen(evt);
            }
        });

        jButton11.setBackground(new java.awt.Color(255, 255, 204));
        jButton11.setFont(new java.awt.Font("Courier New", 3, 24)); // NOI18N
        jButton11.setForeground(new java.awt.Color(0, 0, 0));
        jButton11.setText("AC");
        jButton11.setBorder(new javax.swing.border.MatteBorder(null));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        num2.setBackground(new java.awt.Color(255, 255, 255));
        num2.setFont(new java.awt.Font("Courier New", 3, 24)); // NOI18N
        num2.setForeground(new java.awt.Color(0, 0, 0));
        num2.setText("2");
        num2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        num2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                display_Numers_OnScreen(evt);
            }
        });

        tbn_point.setBackground(new java.awt.Color(204, 204, 255));
        tbn_point.setFont(new java.awt.Font("Courier New", 3, 24)); // NOI18N
        tbn_point.setForeground(new java.awt.Color(0, 0, 0));
        tbn_point.setText(",");
        tbn_point.setBorder(new javax.swing.border.MatteBorder(null));

        num3.setBackground(new java.awt.Color(255, 255, 255));
        num3.setFont(new java.awt.Font("Courier New", 3, 24)); // NOI18N
        num3.setForeground(new java.awt.Color(0, 0, 0));
        num3.setText("3");
        num3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        num3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                display_Numers_OnScreen(evt);
            }
        });

        jButton13.setBackground(new java.awt.Color(204, 204, 255));
        jButton13.setFont(new java.awt.Font("Courier New", 3, 24)); // NOI18N
        jButton13.setForeground(new java.awt.Color(0, 0, 0));
        jButton13.setText("√");
        jButton13.setBorder(new javax.swing.border.MatteBorder(null));

        num4.setBackground(new java.awt.Color(255, 255, 255));
        num4.setFont(new java.awt.Font("Courier New", 3, 24)); // NOI18N
        num4.setForeground(new java.awt.Color(0, 0, 0));
        num4.setText("4");
        num4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        num4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                display_Numers_OnScreen(evt);
            }
        });

        tbn_mult.setBackground(new java.awt.Color(204, 255, 204));
        tbn_mult.setFont(new java.awt.Font("Courier New", 3, 24)); // NOI18N
        tbn_mult.setForeground(new java.awt.Color(0, 0, 0));
        tbn_mult.setText("x");
        tbn_mult.setBorder(new javax.swing.border.MatteBorder(null));
        tbn_mult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operation_Handler(evt);
            }
        });

        num5.setBackground(new java.awt.Color(255, 255, 255));
        num5.setFont(new java.awt.Font("Courier New", 3, 24)); // NOI18N
        num5.setForeground(new java.awt.Color(0, 0, 0));
        num5.setText("5");
        num5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        num5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                display_Numers_OnScreen(evt);
            }
        });

        tbn_minus.setBackground(new java.awt.Color(204, 255, 204));
        tbn_minus.setFont(new java.awt.Font("Courier New", 3, 24)); // NOI18N
        tbn_minus.setForeground(new java.awt.Color(0, 0, 0));
        tbn_minus.setText("-");
        tbn_minus.setBorder(new javax.swing.border.MatteBorder(null));
        tbn_minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operation_Handler(evt);
            }
        });

        num6.setBackground(new java.awt.Color(255, 255, 255));
        num6.setFont(new java.awt.Font("Courier New", 3, 24)); // NOI18N
        num6.setForeground(new java.awt.Color(0, 0, 0));
        num6.setText("6");
        num6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        num6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                display_Numers_OnScreen(evt);
            }
        });

        tbn_add.setBackground(new java.awt.Color(204, 255, 204));
        tbn_add.setFont(new java.awt.Font("Courier New", 3, 24)); // NOI18N
        tbn_add.setForeground(new java.awt.Color(0, 0, 0));
        tbn_add.setText("+");
        tbn_add.setBorder(new javax.swing.border.MatteBorder(null));
        tbn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operation_Handler(evt);
            }
        });

        num7.setBackground(new java.awt.Color(255, 255, 255));
        num7.setFont(new java.awt.Font("Courier New", 3, 24)); // NOI18N
        num7.setForeground(new java.awt.Color(0, 0, 0));
        num7.setText("7");
        num7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        num7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                display_Numers_OnScreen(evt);
            }
        });

        tbn_result.setBackground(new java.awt.Color(102, 153, 255));
        tbn_result.setFont(new java.awt.Font("Courier New", 3, 24)); // NOI18N
        tbn_result.setForeground(new java.awt.Color(0, 0, 0));
        tbn_result.setText("=");
        tbn_result.setBorder(new javax.swing.border.MatteBorder(null));
        tbn_result.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operation_Handler(evt);
            }
        });

        num8.setBackground(new java.awt.Color(255, 255, 255));
        num8.setFont(new java.awt.Font("Courier New", 3, 24)); // NOI18N
        num8.setForeground(new java.awt.Color(0, 0, 0));
        num8.setText("8");
        num8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        num8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                display_Numers_OnScreen(evt);
            }
        });

        jButton18.setBackground(new java.awt.Color(51, 51, 51));
        jButton18.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        jButton18.setForeground(new java.awt.Color(255, 255, 255));
        jButton18.setText("BACK");
        jButton18.setBorder(null);
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        num9.setBackground(new java.awt.Color(255, 255, 255));
        num9.setFont(new java.awt.Font("Courier New", 3, 24)); // NOI18N
        num9.setForeground(new java.awt.Color(0, 0, 0));
        num9.setText("9");
        num9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        num9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                display_Numers_OnScreen(evt);
            }
        });

        tbn_dir.setBackground(new java.awt.Color(204, 255, 204));
        tbn_dir.setFont(new java.awt.Font("Courier New", 3, 24)); // NOI18N
        tbn_dir.setForeground(new java.awt.Color(0, 0, 0));
        tbn_dir.setText("/");
        tbn_dir.setBorder(new javax.swing.border.MatteBorder(null));
        tbn_dir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operation_Handler(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_display, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(num1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(num0, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tbn_point, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tbn_result, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(num2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(16, 16, 16)
                                        .addComponent(num3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btn_off, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tbn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tbn_dir, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(num4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(num5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(num6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(num7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(num8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(num9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tbn_mult, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbn_minus, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tf_display, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbn_dir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_off, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(num7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(num8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(num9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbn_mult, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(num4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(num5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(num6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbn_minus, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(num1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(num2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(num3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tbn_point, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(num0, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tbn_result, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   String str="";
  double total=0;
    private void addToDisplay(String btnText){
        str+=btnText;
        tf_display.setText(str);
    }
    private void display_Numers_OnScreen(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_display_Numers_OnScreen
        // TODO add your handling code here:
        JButton clickedButton = (JButton) evt.getSource();
        addToDisplay(clickedButton.getText());
    }//GEN-LAST:event_display_Numers_OnScreen

 
    
                
    private void operation_Handler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operation_Handler
         
        JButton clickedButton = (JButton) evt.getSource();
        String newOperation=clickedButton.getText();
        if (newOperation=="=") newOperation="";
        double total;
        if (str=="") {
             addToDisplay(newOperation);
            
        }else  if (Calc.containOperation(str)) {
            //// obtenire l'operation
            char op=Calc.extractOperation(str);
            /// obtenire les nomber qui on va les calculer
            double[] numbers=Calc.getNumbers(str);
            total=Calc.calculate(numbers, op, newOperation);
            str=total+newOperation;
             tf_display.setText(str);
        }else {
            JButton m = (JButton) evt.getSource();
            addToDisplay(m.getText());
        }
    }//GEN-LAST:event_operation_Handler

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
         str="";
         total=0;
        tf_display.setText(str);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void btn_offActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_offActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btn_offActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
        str=str.substring(0, str.length()-1);
         tf_display.setText(str);
        
    }//GEN-LAST:event_jButton18ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculatrice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculatrice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculatrice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculatrice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculatrice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_off;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton18;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton num0;
    private javax.swing.JButton num1;
    private javax.swing.JButton num2;
    private javax.swing.JButton num3;
    private javax.swing.JButton num4;
    private javax.swing.JButton num5;
    private javax.swing.JButton num6;
    private javax.swing.JButton num7;
    private javax.swing.JButton num8;
    private javax.swing.JButton num9;
    private javax.swing.JButton tbn_add;
    private javax.swing.JButton tbn_dir;
    private javax.swing.JButton tbn_minus;
    private javax.swing.JButton tbn_mult;
    private javax.swing.JButton tbn_point;
    private javax.swing.JButton tbn_result;
    private javax.swing.JTextField tf_display;
    // End of variables declaration//GEN-END:variables
}
